#
# Very simple makefile for coursework 1. You are free to update this if you
# wish to add files etc., but ensure (a) the executable name is unchanged,
# (b) it works on the gradescope autograder (use "Check submission" first to
# be sure), and (c) the file cwk1_extra.h is unaltered.
#
EXE = cwk1
CC = gcc
CCFLAGS = -Wall -fopenmp

all:
	$(CC) $(CCFLAGS) -o $(EXE) cwk1.c

